name: test_action_package
version: 1.0.0
description: A test package for testing GitHub action.
publish_to: "none"

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  dart_code_metrics: ^5.0.0
  test: ^1.17.9
